from rest_framework import serializers


class PromptSerializer(serializers.Serializer):
    prompt = serializers.CharField(
        max_length=1000,
        help_text="The prompt to send to the AI agent. Maximum length is 1000 characters."

    )

    file_path = serializers.CharField(
        required=False,
        allow_blank=True,
        help_text="Optional folder path to pass to the AI agent."
    )

class ResponseSerializer(serializers.Serializer):
    response = serializers.CharField(
        help_text="The response generated by the AI agent."
    )
